---
title: "R Notebook"
output: html_notebook
---
# Overall revenue Tourism Activities 
```{r}
scot_activ %>%
   filter(tourism_activity == "All") %>%
  ggplot() +
geom_col(aes(x= date_code, y = million_pounds_gbp, fill = date_code)) +
  labs(fill = "Year") +
  labs(
    x = "Year",
    y = "Million Pounds Revenue",
    title = "Scottish Tourism Activity Revenue 2013 - 2019"
  )
```


# Looking at change in accomodation rates

```{r}
scot_accom_raw %>%
  filter(location == "All") %>%
  ggplot() +
   ggtitle("Scottish Transport Methods 2019") +
  ylab("Visits/Million") +
  xlab("Method of Travel") +
  theme(legend.position='none') +
  geom_col(aes(x = date_code, y = value, fill = accommodation_type_and_occupancy))
```

# Looking at transport types 

```{r}
scot_tran %>%
  filter(date_code == "2019" & method_of_travel != "All" & method_of_travel != "Car - own/friends/family") %>%
  group_by(method_of_travel) %>%
  summarise(visits = million_visits) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   geom_col(aes(x = method_of_travel, y = visits, fill = method_of_travel)) +
    ggtitle("Scottish Transport Methods 2019") +
  ylab("Visits/Million") +
  xlab("Method of Travel") +
  scale_y_continuous(breaks = c(5, 10, 15, 20)) +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Bike", "Boat/Ship/Ferry", "Organised Tour", "Regular Bus", "Car Hired", "Caravan/Campervan", "Lorry/Truck/Van", "Other", "Plane", "Taxi", "Train", "Tram", "Tube", "Walked"))
```

```{r}
scot_tran %>%
  filter(date_code == "2013" & method_of_travel != "All" & method_of_travel != "Car - own/friends/family" & method_of_travel != "Motor cycle"
         & method_of_travel != "Bus or Coach - Minibus") %>%
  group_by(method_of_travel) %>%
  summarise(visits = million_visits) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   geom_col(aes(x = method_of_travel, y = visits, fill = method_of_travel)) +
  ggtitle("Scottish Transport Methods 2013") +
  ylab("Visits/Million") +
  xlab("Method of Travel") +
  scale_y_continuous(breaks = c(5, 10, 15, 20)) +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Bike", "Boat/Ship/Ferry", "Organised Tour", "Regular Bus", "Car Hired", "Caravan/Campervan", "Lorry/Truck/Van", "Other", "Plane", "Taxi", "Train", "Tram", "Tube", "Walked")) 
```


```{r}
scot_tran %>%
  filter(date_code == "2013" & method_of_travel != "All" & method_of_travel != "Car - own/friends/family" & method_of_travel != "Motor cycle"
          & method_of_travel != "Bus or Coach - Minibus") %>%
  group_by(method_of_travel) %>%
  summarise(revenue = million_pounds_gbp) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   geom_col(aes(x = method_of_travel, y = revenue, fill = method_of_travel)) +
    ggtitle("Scottish Transport Methods 2013") +
  ylab("Revenue £m") +
  xlab("Method of Travel") +
    scale_y_continuous(breaks = c(200, 400, 600, 800)) +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Bike", "Boat/Ship/Ferry", "Organised Tour", "Regular Bus", "Car Hired", "Caravan/Campervan", "Lorry/Truck/Van", "Other", "Plane", "Taxi", "Train", "Tram", "Tube", "Walked")) 
```

```{r}
scot_tran %>%
  filter(date_code == "2019" & method_of_travel != "All" & method_of_travel != "Car - own/friends/family") %>%
  group_by(method_of_travel) %>%
  summarise(revenue = million_pounds_gbp) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   geom_col(aes(x = method_of_travel, y = revenue, fill = method_of_travel)) +
    ggtitle("Scottish Transport Methods 2019") +
   ylab("Revenue £m") +
  xlab("Method of Travel") +
  scale_y_continuous(breaks = c(200, 400, 600, 800)) +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Bike", "Boat/Ship/Ferry", "Organised Tour", "Regular Bus", "Car Hired", "Caravan/Campervan", "Lorry/Truck/Van", "Other", "Plane", "Taxi", "Train", "Tram", "Tube", "Walked"))
```
```{r}
scot_tran %>%
  filter(date_code == "2019")
```
 # Model building
 
```{r}
library(car)
library(tidyverse)
library(modelr)

# visualisation packages
library(GGally)

scot_demo %>%
   filter(method_of_travel != "All" & method_of_travel != "Other" & method_of_travel != "Lorry/Truck/Van") %>%
  ggpairs()

mod1a <- lm(million_pounds_gbp ~ million_visits, data = scot_tran)
mod1a

```


```{r}
summary(mod1a)
```

```{r}
par(mfrow = c(2, 2))
plot(mod1a)
```

# A model for demographics 

```{r}
scot_demo %>%
  filter(age != "All" | marital_status != "All" | gender != "All" | 
           employment_status == "All" | children != "All" | 
           access_to_car != "All" | social_grade != "All") %>%
   select(-million_visits) %>%
  ggpairs()
```

# Build a model 

```{r}
 model_set <- scot_demo %>% 
     filter(age != "All") %>%
  # filter(employment_status != "All") %>%
  # filter(access_to_car != "All") %>%
  #           filter(social_grade != "All") 
   
mod2a <- lm(million_pounds_gbp ~ age + access_to_car + social_grade + employment_status, model_set)
mod2a
```




 # age + access_to_car + social_grade + 
    employment_status has a 0.73 predictor of 
```{r}
summary(mod2a)
```

```{r}
par(mfrow = c(2, 2))
plot(mod2a)
```

# What kind of activity generates the most visits to sites?

```{r}
scot_activ %>%
  filter(date_code == "2019" & tourism_activity != "All") %>%
  group_by(tourism_activity) %>%
  summarise(visits = million_visits) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_col(aes(x = tourism_activity, y = visits, fill = tourism_activity)) +
   ggtitle("Scottish Tourist Activity Visits 2019") +
   ylab("Visits/million") +
  xlab("Tourist Activities") +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Spa Day", "Day Trip", "Entertainment", "Exploring", "Leisure Activities", "Night Out", "Outdoor Leisure", "Shopping", "Personal Events", "Public Events", "Sport Participation", "Visiting friends or family", "Visitor Attraction", "Live Sport", "Out for a meal"))
```

```{r}
scot_activ %>%
  filter(date_code == "2013" & tourism_activity != "All") %>%
  group_by(tourism_activity) %>%
  summarise(visits = million_visits) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_col(aes(x = tourism_activity, y = visits)) +
  scale_x_discrete(labels = c("Spa Day", "Day Trip", "Entertainment", "Exploring", "Leisure Activities", "Night Out", "Outdoor Leisure", "Shopping", "Personal Events", "Public Events", "Sport Participation", "Visiting friends or family", "Visitor Attraction", "Live Sport", "Out for a meal"))
```

```{r}
scot_activ %>%
  filter(date_code == "2019")
```

```{r}
scot_activ %>%
  filter(date_code == "2013")
```

```{r}
scot_activ %>%
  filter(date_code == "2013" & tourism_activity != "All") %>%
  group_by(tourism_activity) %>%
  summarise(revenue = million_pounds_gbp) %>%
  ggplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_col(aes(x = tourism_activity, y = revenue, fill = tourism_activity)) +
   ggtitle("Scottish Tourist Activity Revenue 2013") +
   ylab("Revenue per Million") +
  xlab("Tourist Activities") +
  theme(legend.position='none') +
  scale_x_discrete(labels = c("Spa Day", "Day Trip", "Entertainment", "Exploring", "Leisure Activities", "Night Out", "Outdoor Leisure", "Shopping", "Personal Events", "Public Events", "Sport Participation", "Visiting friends or family", "Visitor Attraction", "Live Sport", "Out for a meal"))
```

```{r}
scot_loca %>%
  filter(date_code == "2019" & type_of_location_visited != "All areas") %>%
  group_by(type_of_location_visited) %>%
  summarise(visits = million_visits) %>%
  ggplot() +
  scale_x_discrete(labels = c("City", "Rural", "Seaside - Beach", "Seaside - other", "Seaside - Resort", "Town", "Village")) +
  theme(legend.position='none') +
  ggtitle("Scottish Tourist Locations 2019") +
   ylab("Visits per Million") +
  xlab("Type of Locations Visited") +
   geom_col(aes(x = type_of_location_visited, y = visits, fill = type_of_location_visited))
```


```{r}
scot_loca %>%
  filter(date_code == "2019" & type_of_location_visited != "All areas") %>%
  group_by(type_of_location_visited) %>%
  summarise(revenue = million_pounds_gbp) %>%
  ggplot() +
  scale_x_discrete(labels = c("City", "Rural", "Seaside - Beach", "Seaside - other", "Seaside - Resort", "Town", "Village")) +
  theme(legend.position='none') +
  ggtitle("Scottish Tourist Locations 2019") +
   ylab("Revenue per Million") +
  xlab("Type of Locations Visited") +
   geom_col(aes(x = type_of_location_visited, y = revenue, fill = type_of_location_visited))
```
```{r}
scot_loca %>%
  filter(type_of_location_visited != "All areas") %>%
  ggplot() + 
  ggtitle("Scottish Tourist Locations 2019") +
   ylab("Visits per Million") +
  xlab("Revenue per Million") +
  labs(col = "Year", shape = "Location›") +
  geom_point(aes(x = million_pounds_gbp, y = million_visits, colour = date_code, shape = type_of_location_visited))
```

```{r}
country_dom_tour <- dom_tour %>%
  filter(feature_code == "S92000003")
```


```{r}
scot_accom_raw_urban <- scot_accom_raw %>%
  filter(Location == "Large Urban Areas")
```


```{r}
scot_demo %>%
  filter(age != "All" & date_code == "2019") %>%
   group_by(age) %>%
   summarise(avg_spend = million_pounds_gbp/million_visits)
  # arrange(desc(million_pounds_gbp))
```

```{r}
country_dom_tour %>%
  filter(breakdown_of_domestic_tourism == "Visits" & date_code != "2009-2011" & date_code != "2010-2012"
         & region_of_residence != "All of GB") %>%
  ggplot()+
  ggtitle("Scottish Tourist Region of Residency 2019") +
   ylab("Visits per Thousand") +
  xlab("Year") +
  labs(fill = "Region of Residence") +
    scale_x_discrete(labels = c("2013", "2014", "2015", "2016", "2017", "2018", "2019")) +
  geom_col(aes(x = date_code, y = value, fill = region_of_residence))
```

```{r}
country_dom_tour %>%
  filter(date_code == "2017-2019" & breakdown_of_domestic_tourism == "Expenditure") %>%
  group_by(region_of_residence) %>%
    summarise(value)
```



```{r}
scot_accom_raw %>%
  filter(date_code == "2019" & location == "Large Urban Areas"& accommodation_type_and_occupancy != "Hotels - Bed Occupancy"
         & accommodation_type_and_occupancy != "Hostels - Bed Occupancy" & accommodation_type_and_occupancy != "Guest House/B&B - Bed Occupancy") %>%
  group_by(accommodation_type_and_occupancy) %>%
  summarise(occupancy = value) %>%
  radarchart::chartJSRadar(labs = c("Caravan/Camping", "B&B", "Hotels", "Self Catering"))
  
  
  
```

```{r}
library(radarchart)
library(fmsb)
```

```{r}
scot_accom_raw %>%
  filter(date_code == "2019" & location == "Remote Rural"& accommodation_type_and_occupancy != "Hotels - Bed Occupancy"
         & accommodation_type_and_occupancy != "Hostels - Bed Occupancy" & accommodation_type_and_occupancy != "Guest House/B&B - Bed Occupancy") %>%
  group_by(accommodation_type_and_occupancy) %>%
  summarise(occupancy = value) %>%
  radarchart::chartJSRadar(labs = c("Caravan/Camping", "B&B", "Hotels", "Self Catering"))

```



```{r}
scot_accom_raw %>%
  filter(date_code == "2013" & location == "Large Urban Areas"& accommodation_type_and_occupancy != "Hotels - Bed Occupancy"
         & accommodation_type_and_occupancy != "Hostels - Bed Occupancy" & accommodation_type_and_occupancy != "Guest House/B&B - Bed Occupancy") %>%
  group_by(accommodation_type_and_occupancy) %>%
  summarise(occupancy = value) %>%
  radarchart::chartJSRadar(labs = c("Caravan/Camping", "B&B", "Hotels", "Self Catering"))
```

```{r}
scot_accom_raw %>%
  filter(date_code == "2013" & location == "Remote Rural" & accommodation_type_and_occupancy != "Hotels - Bed Occupancy"
         & accommodation_type_and_occupancy != "Hostels - Bed Occupancy" & accommodation_type_and_occupancy != "Guest House/B&B - Bed Occupancy") %>%
  group_by(accommodation_type_and_occupancy) %>%
  summarise(occupancy = value) %>%
  radarchart::chartJSRadar(labs = c("Caravan/Camping", "B&B", "Hotels", "Self Catering"))

```



```{r}
scot_activ_raw %>%
   filter(units == "Million Visits" & tourism_activity != "All") %>%
  # group_by(tourism_activity) %>%
  # summarise(revenue = million_pounds_gbp) %>%
  ggplot() +
  # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_line(aes(x = date_code, y = value, colour = tourism_activity)) +
  geom_point(aes(x = date_code, y = value, colour = tourism_activity)) +
   ggtitle("Scottish Tourist Activity Visits") +
   ylab("Visits per Million") +
  xlab("Year") +
  labs(colour = "Tourist Activity") +
  scale_colour_discrete(labels = c("Spa Day", "Day Trip", "Entertainment", "Exploring", "Leisure Activities", "Night Out", "Outdoor Leisure", "Shopping", "Personal Events", "Public Events", "Sport Participation", "Visiting friends or family", "Visitor Attraction", "Live Sport", "Out for a meal"))
```

